apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: melosys-api-runner
  namespace: teammelosys
  labels:
    team: teammelosys
spec:
  image: {{ IMAGE }}
  vault:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1500m
      memory: 1536Mi
  env:
    - name: RUNNER_LABELS
      value: {{ CLUSTER }},java-11,java-15
