apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sendsoknad-runner
  namespace: team-soknad
  labels:
    team: team-soknad
spec:
  image: {{ IMAGE }}
  vault:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 4096Mi
    requests:
      cpu: 1500m
      memory: 2048Mi
  env:
    - name: RUNNER_LABELS
      value: {{ CLUSTER }},java-8,java-11,java-15
